### ISSUE TITLE
cubecell_board_pro type is not kown by platformio

### ISSUE THREAD

**Issue by hansju-11** [HelTecAutomation/platform-asrmicro650x#10]
Processing cubecell_board_pro (platform: asrmicro650x; framework: arduino; board: cubecell_board_pro)
--------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'cubecell_board_pro'
========================================= [FAILED] Took 1.00 seconds =========================================

I'm running platformio:   v2.3.2
Core 5.1.1,   Home 3.3.4

**Comment by valeros** [comment]
Hi @hansju-11 ! Support for the `cubecell_board_pro` hasn't been released yet, so you need to use the upstream version of the platform:
```ini
[env:cubecell_board_pro]
platform = https://github.com/HelTecAutomation/platform-asrmicro650x.git
framework = arduino
board = cubecell_board_pro

```

**Comment by hansju-11** [comment]
Thx for the fast answer.
I will do "an upstream" build,

perfect it is working.
