### ISSUE TITLE
"packages/framework-arduinoasrmicro650x/cores/asr650x/lora/radio" not found in c_cpp_properties.json

### ISSUE THREAD

**Issue by edulbastos** [HelTecAutomation/platform-asrmicro650x#11]
Hi,

After upgrading from asr650x@1.2.0 to asr650x@1.3.1 in plataformio, there´s one subdirectory called 'radio' inside 'lora' that´s missing. I can compile and link, but is there any hint how to remove this error?

Regards

**Comment by valeros** [comment]
Hi @edulbastos ! It's already fixed in the development branch and will be available in the next release. As for now, you can use the upstream version of the platform:
```ini
[env:cubecell_gps]
platform = https://github.com/HelTecAutomation/platform-asrmicro650x.git
framework = arduino
board = cubecell_gps
```

**Comment by edulbastos** [comment]
Hi valeros,

Thanks a lot for your support.

Regards,
