### ISSUE TITLE
Servo library support

### ISSUE THREAD

**Issue by snebot-bg** [HelTecAutomation/platform-asrmicro650x#12]
When will the servo library be supported on platformio? I know there is support for servos on the [Arduino repository](https://github.com/HelTecAutomation/CubeCell-Arduino) but our current project relies on platformio.

Thank you.

**Comment by valeros** [comment]
Hi @snebot-bg ! This library is not available in the latest stable Arduino core v1.3.0. As soon as a new release of the Arduino core is published we will update the framework package accordingly.

**Comment by ivankravets** [comment]
Resoled in https://github.com/HelTecAutomation/platform-asrmicro650x/commit/d7ba4e91b88224b9c2248a01720b4d123d6d0723
