### ISSUE TITLE
New release needed - its been 6 months

### ISSUE THREAD

**Issue by jezdd** [HelTecAutomation/platform-asrmicro650x#17]
Can we publish a new and up to date release please

**Comment by Max-Plastix** [comment]
That would be great!  Specifically we need the v1.4.0 release from https://github.com/HelTecAutomation/CubeCell-Arduino

**Comment by 1rabbit** [comment]
Agreed, especially when considering v1.3.0 issues

**Comment by philltran** [comment]
A v1.4.0 release would be awesome. Let us know how we can help.

**Comment by ioeides** [comment]
@Heltec-Aaron-Lee 
could you please address this?

**Comment by ivankravets** [comment]
Resolved in https://github.com/HelTecAutomation/platform-asrmicro650x/commit/d7ba4e91b88224b9c2248a01720b4d123d6d0723

Please upgrade to the latest 1.4.0 version of dev-platform https://registry.platformio.org/platforms/heltecautomation/asrmicro650x/versions

**Comment by philltran** [comment]
Thank you.

**Comment by ivankravets** [comment]
Happy coding with PlatformIO! 🚀 

P.S: https://community.platformio.org/t/platformio-is-a-ukrainian-project-please-help-us-stop-the-war/26330

**Comment by jezdd** [comment]
Thanks, it just occurred to me that you guys will have other things on your mind - our thoughts are with all those in Ukraine right now

**Comment by philltran** [comment]
I feel so insensitive. I did not realize Platform.io is Ukrainian. I pray you and your families are safe.
