### ISSUE TITLE
platforms/asrmicro650x.rst deleted

### ISSUE THREAD

**Issue by SebDominguez** [HelTecAutomation/platform-asrmicro650x#19]
see https://github.com/platformio/platformio-docs/issues/262#issuecomment-1202192252

**Comment by ivankravets** [comment]
we tem

**Comment by Heltec-Aaron-Lee** [comment]
@ivankravets I had sent an email to you, did you receive that?

**Comment by ivankravets** [comment]
Hi @Heltec-Aaron-Lee , no, we didn't receive it. Could you resend it again? Thanks!

**Comment by Heltec-Aaron-Lee** [comment]
Already sent again, did you see that? Or can you please check your spam?

**Comment by ivankravets** [comment]
Resolved in https://github.com/HelTecAutomation/platform-heltec-cubecell
