### ISSUE TITLE
Join after reset

### ISSUE THREAD

**Issue by rony-vargas** [HelTecAutomation/platform-asrmicro650x#3]
I am trying to avoid a join every time the device resets and I am using this code line:
`bool keepNet = LORAWAN_NET_RESERVE;`

and `platformio.ini` this flag is set: `board_build.arduino.lorawan.net_reserve = ON`

But it doesn't take any effect, every reset the device goes and re-join

**Comment by valeros** [comment]
Hi @rony-vargas ! Does it work in Arduino IDE?

**Comment by rony-vargas** [comment]
Hi @valeros  It doesn't work on Arduino IDE as well:
Arduino IDE Version: 1.8.13
When looking to debug prints, device prints `+KeepNet=0`
![image](https://user-images.githubusercontent.com/49657944/97490995-8fb39380-192f-11eb-92ab-abe634ee7f36.png)
But I have confirmed it is ON on both, Arduino and PlatformIO
![image](https://user-images.githubusercontent.com/49657944/97491029-9cd08280-192f-11eb-9fb9-f1639838d6e6.png)

platformio.ini
```
[env:cubecell_board_plus]
platform = asrmicro650x
board = cubecell_board_plus
framework = arduino
lib_deps = sabas1080/CayenneLPP@^1.1.0
upload_port = COM17
monitor_speed=115200
board_build.arduino.lorawan.region = US915
board_build.arduino.lorawan.adr = ON
board_build.arduino.lorawan.debug_level = FREQ_AND_DIO
board_build.arduino.lorawan.at_support = ON
board_build.arduino.lorawan.uplinkmode = UNCONFIRMED
board_build.arduino.lorawan.net_reserve = ON
```

**Comment by valeros** [comment]
Since the problem is not specific solely to PlatformIO, please forward the issue here https://github.com/HelTecAutomation/ASR650x-Arduino/issues where it should get more attention.
