### ISSUE TITLE
Outdated `framework-arduinoasrmicro650x` package installed

### ISSUE THREAD

**Issue by aparcar** [HelTecAutomation/platform-asrmicro650x#5]
Hi, installing this via Platformio install package `framework-arduinoasrmicro650x` with an outdated LoRa library. The US915 preamble is still set to 14 which is incompatible with the HT-M00 gateway.

```
framework-arduinoasrmicro650x/cores/asr650x/loramac/mac/region/RegionUS915.c
604:    Radio.SetTxConfig( MODEM_LORA, phyTxPower, 0, bandwidth, phyDr, 1, 14, false, true, 0, 0, false, 3e3 );
```

**Comment by valeros** [comment]
Hi @aparcar ! We use stable releases from this repo https://github.com/HelTecAutomation/ASR650x-Arduino/releases. Once there is a new version we will update the package accordingly.
