### ISSUE TITLE
Can we update this to v1.3 ?

### ISSUE THREAD

**Issue by jezdd** [HelTecAutomation/platform-asrmicro650x#8]
HelTec have now updated the core to 1.3 so can the PlatformIO release reflect this please?

**Comment by eikaramba** [comment]
yes please @Heltec-Aaron-Lee

**Comment by jezdd** [comment]
anyone home?

**Comment by Heltec-Aaron-Lee** [comment]
We had submitted the 1.3.0 upgrade, waiting for the platfrom.io official review.

**Comment by lnlp** [comment]
"Major update"

What has been updated. Where are the release notes?

**Comment by jezdd** [comment]
> "Major update"
> 
> What has been updated. Where are the release notes?

see here https://github.com/HelTecAutomation/CubeCell-Arduino

**Comment by jezdd** [comment]
1.3.1 compiles clean
